{
 "title": "option-greeks",
 "time": { "from": "2024-08-30T03:46:18.000Z", "to": "2024-08-30T07:14:12.000Z" },
 "panels": [
  {
   "title": "Vega",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"nifty\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\n  |> filter(fn: (r) => r[\"_field\"] == \"call_vega\" or r[\"_field\"] == \"put_vega\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"])  // Ensure the data is sorted by time"
    }
   ]
  },
  {
   "title": "vega increase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"call_vega\" or r[\"_field\"] == \"put_vega\")\r\n  |> increase()\r\n  |> yield(name: \"increase\")"
    }
   ]
  },
  {
   "title": "Implied Volatility",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "  from(bucket: \"nifty\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\n  |> filter(fn: (r) => r[\"_field\"] == \"put_impliedVolatility\" or r[\"_field\"] == \"call_impliedVolatility\")\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "IV increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"call_impliedVolatility\" or r[\"_field\"] == \"put_impliedVolatility\")\r\n  |> increase()\r\n  |> yield(name: \"increase\")"
    }
   ]
  },
  {
   "title": "Theta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "  from(bucket: \"nifty\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\n  |> filter(fn: (r) => r[\"_field\"] == \"call_theta\" or r[\"_field\"] == \"put_theta\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"])  // Ensure the data is sorted by time\n"
    }
   ]
  },
  {
   "title": "Theta increase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"put_theta\" or r[\"_field\"] == \"call_theta\")\r\n  |> increase()\r\n  |> yield(name: \"increase\")"
    }
   ]
  },
  {
   "title": "Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"nifty\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\n  |> filter(fn: (r) => r[\"_field\"] == \"call_callDelta\" or r[\"_field\"] == \"put_putDelta\")\n"
    }
   ]
  },
  {
   "title": "Delta increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"call_callDelta\" or r[\"_field\"] == \"put_putDelta\")\r\n  |> increase()\r\n  |> yield(name: \"increase\")"
    }
   ]
  },
  {
   "title": "gamma",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"put_gamma\" or r[\"_field\"] == \"call_gamma\")"
    }
   ]
  },
  {
   "title": "gamma increase",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"put_gamma\" or r[\"_field\"] == \"call_gamma\")\r\n  |> increase()\r\n  |> yield(name: \"increase\")"
    }
   ]
  },
  {
   "title": "Angles",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "import \"contrib/anaisdg/statsmodels\"\r\nimport \"math\"\r\n\r\n// Function to convert slope to degrees\r\nconvertSlopeToAngle = (slope) => math.atan(x: slope) * 180.0 / math.pi\r\n\r\n// Query for call vega angle\r\ncall_vega_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"call_vega\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"Vega Call\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n// Query for put vega angle\r\nput_vega_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"put_vega\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"Vega Put\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n  // Query for put vega angle\r\ncall_iv_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"call_impliedVolatility\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"IV Call\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n  put_iv_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"put_impliedVolatility\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"IV Put\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n  call_delta_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"call_callDelta\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"Delta Call\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n  put_delta_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"put_putDelta\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"Delta Put\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n  call_theta_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"call_theta\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"Theta Call\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n  put_theta_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"put_theta\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"Theta Put\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n  call_gamma_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"call_gamma\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"Gamma Call\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n  put_gamma_angle = from(bucket: \"nifty\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"greeks_differences\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"put_gamma\")\r\n  |> statsmodels.linearRegression()\r\n  |> map(fn: (r) => ({\r\n      title: \"Gamma Put\",\r\n      _value: convertSlopeToAngle(slope: r.slope),\r\n      _time: r._time\r\n  }))\r\n  |> last()  // Get the most recent slope value\r\n\r\n// Combine both queries into a single table\r\ncombined_angles = union(tables: [call_vega_angle, put_vega_angle, call_iv_angle, put_iv_angle, call_delta_angle, put_delta_angle, call_theta_angle, put_theta_angle, call_gamma_angle, put_gamma_angle])\r\n  |> yield(name: \"combined_vega_angles\")\r\n"
    }
   ]
  }
 ]
}